---
fas2discourse_hostname: "fas2discourse.hostna.me"
fas2discourse_namespace: "fas2discourse-operator"
fas2discourse_project_description: "The fas2discourse-operator is responsible for synchronising group membership for users between Discourse and IPA."
fas2discourse_keytab_file: "OVERRIDEME WITH A FILE LOOKUP"
fas2discourse_discourse_apikey: "OVERRIDEME WITH A DISCOURSE APIKEY"
