---
apiVersion: image.openshift.io/v1
kind: List
items:
  # ImageStream for Fedora image
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        build: fedora-ostree-pruner
      name: fedora
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: "41"
          from:
            kind: DockerImage
            name: registry.fedoraproject.org/fedora:41
          importPolicy:
            scheduled: true
          referencePolicy:
            type: Source
  # ImageStream for resulting built fedora-ostree-pruner-img
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      labels:
        build: fedora-ostree-pruner
      name: fedora-ostree-pruner-img
