---
- name: Check if faf is installed
  command: rpm -q faf
  changed_when: false

- name: Add user retrace to faf db
  postgresql_user:
    db: faf
    name: retrace
    priv: ALL
    role_attr_flags: SUPERUSER
    state: present
  become: yes
  become_user: postgres
