---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blockerbugs
  name: blockerbugs
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: blockerbugs
    service: blockerbugsN
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blockerbugs
  name: qa-landing
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: blockerbugs
    service: qa-landingN
