---
pkgs_list:
  - policycoreutils-python-utils

zabbix_pkgs_list:
  - zabbix-agent
  - zabbix # provides zabbix_sender
  - zabbix-selinux
  - bc
  - ncurses-compat-libs  # Needed for some megacli tools and raid monitoring checks through zabbix_sender

zabbix_agentd: /etc/zabbix_agentd.conf

zabbix_agentd_dir: /etc/zabbix/zabbix_agentd.d
