---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "languages-storage{{ '-stg' if env == 'staging' else '' }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
{%    if env == 'staging' %}
      storage: 40Gi
{%    else %}
      storage: 70Gi
{%    endif %}
  storageClassName: ""
  volumeName: "languages-storage{{ '-stg' if env == 'staging' else '' }}"
