apiVersion: apps/v1
kind: Deployment
metadata:
  name: mote-worker
  labels:
    app: mote-worker
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"mote:latest","namespace":"mote"},"fieldPath":"spec.template.spec.containers[?(@.name==\"mote-worker\")].image","pause":"false"}]
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mote-worker
  template:
    metadata:
      labels:
        app: mote-worker
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/mote/mote
        command:
        - python
        - -m
        - mote.worker
        env:
        - name: REDIS_URL
          value: "redis://redis.{{ app }}.svc.cluster.local"
        - name: LOGLEVEL
          value: "20"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: password
        name: mote-worker
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /srv
          name: meetbot
        - mountPath: /opt/app/mote/config.py
          name: mote-config
          readOnly: true
          subPath: config.py
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: '0'
            memory: 200Mi
      volumes:
      - name: meetbot
        persistentVolumeClaim:
          claimName: meetbot-storage
      - configMap:
          defaultMode: 420
          name: mote
        name: mote-config
      restartPolicy: Always
