---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mote
data:
  config.py: |
    MEETING_DIR = "/srv/web/meetbot"
    MEETBOT_URL = "https://meetbot{{env_suffix}}.fedoraproject.org"
    MEETBOT_RAW_URL = "https://meetbot-raw{{env_suffix}}.fedoraproject.org"
    DATAGREPPER_BASE_URL = "https://apps{{env_suffix}}.fedoraproject.org"
    RECOGNIITION_PATTERN = r"(.*)[\-\.]([0-9]{4}-[0-9]{2}-[0-9]{2})-([0-9]{2}\.[0-9]{2})"
    CACHE_TYPE = "RedisCache"
    CACHE_REDIS_URL = "redis://redis.{{ app }}.svc.cluster.local"
    CACHE_DEFAULT_TIMEOUT = 0
