---
galaxy_info:
  author: sorki
  description: Retrace Server deployment
  license: BSD
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 33
        - 34
        - 35
  galaxy_tags:
    - system
