---
apiVersion: v1
kind: Service
metadata:
  name: discourse2fedmsg-web
  labels:
    app: discourse2fedmsg
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: discourse2fedmsg
    deploymentconfig: discourse2fedmsg
