---
apiVersion: image.openshift.io/v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: release-monitoring-web
    labels:
      build: release-monitoring-web
kind: List
metadata: {}
