apiVersion: v1
kind: List
items:
# ImageStream for Fedora image
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: coreos-koji-tagger
    name: fedora
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: "34"
      from:
        kind: DockerImage
        name: registry.fedoraproject.org/fedora:34
      importPolicy: 
        scheduled: true
      referencePolicy:
        type: Source
# ImageStream for resulting built coreos-koji-tagger-img
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: coreos-koji-tagger
    name: coreos-koji-tagger-img
