---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "sysadmin-openshift"
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "sysadmin-openshift"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
