---
apiVersion: image.openshift.io/v1
kind: List
items:
# ImageStream for Fedora 36 image
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: compose-tracker
    name: fedora
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: "38"
      from:
        kind: DockerImage
        name: registry.fedoraproject.org/fedora:38
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
# ImageStream for resulting built compose-tracker-img
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: compose-tracker
    name: compose-tracker-img
