apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: testdays-build
  labels:
    environment: "testdays"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: testdays:latest
  source:
    type: Git
    git:
      uri: https://pagure.io/fedora-qa/testdays-web.git
{% if env == 'staging' %}
      ref: "develop"
{% else %}
      ref: "master"
{% endif %}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/python-39
  triggers:
  - type: ConfigChange
  - type: ImageChange
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: resultsdb-build
  labels:
    environment: "resultsdb"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: resultsdb:latest
  source:
    type: Git
    git:
      uri: https://pagure.io/taskotron/resultsdb.git
      ref: "legacy_testdays"
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/python-39
  triggers:
  - type: ConfigChange
  - type: ImageChange
