---
apiVersion: v1
kind: Service
metadata:
  name: flask-oidc-dev
  labels:
    app: flask-oidc-dev
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: flask-oidc-dev
    deploymentconfig: flask-oidc-dev
