---
- hosts: os_control_stg:os_control
  user: root
  gather_facts: false

  vars_files:
    - /srv/web/infra/ansible/vars/global.yml
    - "/srv/private/ansible/vars.yml"
    - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  tasks:
    - name: Fas2discourse Role
      include_role:
        name: fas2discourse
        tasks_from: create-keytab
    - name: Fas2discourse Role
      include_role:
        name: fas2discourse
        tasks_from: administration-tasks
