---
- hosts: os_control_stg:os_control
  gather_facts: false

  roles:
  - role: openshift/sysadmin-openshift
    appowners:
    - asaleh
    - darknao
    - dkirwan
    - jrichardson
    - kevin
    - lenkaseg
    - mobrien
    - scoady
    - siddharthvipul1
    - t0xic0der
    - ryanlerch
